cask_args appdir: '/Applications'
tap "phinze/cask"
tap "argon/mas"

brew "argon/mas/mas"
brew "ctags"
brew "ffmpeg"
brew "git"
brew "imagemagick"
brew "lua"
brew "luajit"
brew "memcached"
brew "mercurial"
brew "mysql"
brew "nkf"
brew "node"
brew "nspr"
brew "openssl"
brew "phantomjs"
brew "python"
brew "qt5"
brew "rbenv"
brew "readline"
brew "reattach-to-user-namespace"
brew "redis"
brew "ruby-build"
brew "sqlite"
brew "the_silver_searcher"
brew "tree"
brew "x264"
brew "zsh"
brew "pyenv"
brew "envchain"
brew "postgresql"
brew "awscli"

tap "caskroom/cask"

cask "iterm2"
cask "google-chrome"
cask "firefox"
cask "transmit"
cask "playonmac"
cask "vlcstreamer"
cask "vlc"
cask "java"
cask "android-studio"
cask "jetbrains-toolbox"

tap "caskroom/fonts"
cask "font-source-code-pro"
